### ISSUE TITLE
[BUG] Cannot create the idm server

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#298]
**Qubinode Version**  
Qubinode releasev2.42

**Describe the bug**
Fail to deploy the idm server 

**To Reproduce**
1. ./qubinode-installer -p idm

**Expected behavior**
idm server should be created

**Screenshots**
Here is the error:

`TASK [ipaserver : Install - Setup CA] ********************************************************************************************
Wednesday 28 October 2020  22:17:29 +0800 (0:00:06.543)       0:07:04.097 ***** 
fatal: [qbn-dns01]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 192.168.1.139 closed.
  module_stdout: |-
    Failed to configure CA instance: CalledProcessError(Command ['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmp_cktvjly'] returned non-zero exit status 1: 'Notice: Trust flag u is set automatically if the private key is present.\nERROR: Exception: Server unreachable due to SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)\n  File "/usr/lib/python3.6/site-packages/pki/server/pkispawn.py", line 562, in main\n    scriptlet.spawn(deployer)\n  File "/usr/lib/python3.6/site-packages/pki/server/deployment/scriptlets/configuration.py", line 836, in spawn\n    request_timeout=status_request_timeout,\n  File "/usr/lib/python3.6/site-packages/pki/server/deployment/pkihelper.py", line 911, in wait_for_startup\n    raise Exception(\'Server unreachable due to SSL error: %s\' % reason) from exc\n\n')
    See the installation logs and the following files/directories for more information:
      /var/log/pki/pki-tomcat
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py", line 188, in spawn_instance
        ipautil.run(args, nolog=nolog_list)
      File "/usr/lib/python3.6/site-packages/ipapython/ipautil.py", line 598, in run
        p.returncode, arg_string, output_log, error_log
    ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmp_cktvjly'] returned non-zero exit status 1: 'Notice: Trust flag u is set automatically if the private key is present.\nERROR: Exception: Server unreachable due to SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)\n  File "/usr/lib/python3.6/site-packages/pki/server/pkispawn.py", line 562, in main\n    scriptlet.spawn(deployer)\n  File "/usr/lib/python3.6/site-packages/pki/server/deployment/scriptlets/configuration.py", line 836, in spawn\n    request_timeout=status_request_timeout,\n  File "/usr/lib/python3.6/site-packages/pki/server/deployment/pkihelper.py", line 911, in wait_for_startup\n    raise Exception(\'Server unreachable due to SSL error: %s\' % reason) from exc\n\n')
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/home/louie/.ansible/tmp/ansible-tmp-1603894649.9852703-49062-213411280799314/AnsiballZ_ipaserver_setup_ca.py", line 102, in <module>
        _ansiballz_main()
      File "/home/louie/.ansible/tmp/ansible-tmp-1603894649.9852703-49062-213411280799314/AnsiballZ_ipaserver_setup_ca.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/louie/.ansible/tmp/ansible-tmp-1603894649.9852703-49062-213411280799314/AnsiballZ_ipaserver_setup_ca.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.ipaserver_setup_ca', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ipaserver_setup_ca_payload_lyrpgyur/ansible_ipaserver_setup_ca_payload.zip/ansible/modules/ipaserver_setup_ca.py", line 353, in <module>
      File "/tmp/ansible_ipaserver_setup_ca_payload_lyrpgyur/ansible_ipaserver_setup_ca_payload.zip/ansible/modules/ipaserver_setup_ca.py", line 315, in main
      File "/usr/lib/python3.6/site-packages/ipaserver/install/ca.py", line 355, in install_step_0
        pki_config_override=options.pki_config_override,
      File "/usr/lib/python3.6/site-packages/ipaserver/install/cainstance.py", line 480, in configure_instance
        self.start_creation(runtime=runtime)
      File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 603, in start_creation
        run_step(full_msg, method)
      File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 589, in run_step
        method()
      File "/usr/lib/python3.6/site-packages/ipaserver/install/cainstance.py", line 596, in __spawn_instance
        nolog_list=nolog_list
      File "/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py", line 190, in spawn_instance
        self.handle_setup_error(e)
      File "/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py", line 423, in handle_setup_error
        raise RuntimeError("%s configuration failed." % self.subsystem)
    RuntimeError: CA configuration failed.
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1`

**Comment by tosin2013** [comment]
THis should be fixed in dev branch 
https://github.com/Qubinode/qubinode-installer/commit/08187c80234147461f593fce50643c3376ce4a8f
