### ISSUE TITLE
[BUG] IDM Deployment Failed: "DNS zone already exists" root errors 

### ISSUE THREAD

**Issue by wadebee** [Qubinode/qubinode-installer#318]
TASK [ipaserver : Install - Server installation test] ***************************************************************
Tuesday 26 January 2021  20:46:45 -0500 (0:00:00.029)       0:01:35.099 ******* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ipapython.dnsutil.DNSZoneAlreadyExists: DNS zone . already exists in DNS and is handled by server(s): ['a.root-servers.net.', 'b.root-servers.net.', 'c.root-servers.net.', 'd.root-servers.net.', 'e.root-servers.net.', 'f.root-servers.net.', 'g.root-servers.net.', 'h.root-servers.net.', 'i.root-servers.net.', 'j.root-servers.net.', 'k.root-servers.net.', 'l.root-servers.net.', 'm.root-servers.net.']
fatal: [qbn-dns01]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 10.0.0.44 closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/home/admin/.ansible/tmp/ansible-tmp-1611712005.409519-153016-87312541499365/AnsiballZ_ipaserver_test.py", line 102, in <module>
        _ansiballz_main()
      File "/home/admin/.ansible/tmp/ansible-tmp-1611712005.409519-153016-87312541499365/AnsiballZ_ipaserver_test.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/admin/.ansible/tmp/ansible-tmp-1611712005.409519-153016-87312541499365/AnsiballZ_ipaserver_test.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.ipaserver_test', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ipaserver_test_payload_grz_2nnj/ansible_ipaserver_test_payload.zip/ansible/modules/ipaserver_test.py", line 1070, in <module>
      File "/tmp/ansible_ipaserver_test_payload_grz_2nnj/ansible_ipaserver_test_payload.zip/ansible/modules/ipaserver_test.py", line 785, in main
      File "/usr/lib/python3.6/site-packages/ipapython/dnsutil.py", line 383, in check_zone_overlap
        raise DNSZoneAlreadyExists(zone=zone.to_text(), ns=ns)
    ipapython.dnsutil.DNSZoneAlreadyExists: DNS zone . already exists in DNS and is handled by server(s): ['a.root-servers.net.', 'b.root-servers.net.', 'c.root-servers.net.', 'd.root-servers.net.', 'e.root-servers.net.', 'f.root-servers.net.', 'g.root-servers.net.', 'h.root-servers.net.', 'i.root-servers.net.', 'j.root-servers.net.', 'k.root-servers.net.', 'l.root-servers.net.', 'm.root-servers.net.']
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by flyemsafe** [comment]
This was fixed in 2.4.5.
